# Generated by Django 3.1.3 on 2020-12-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='diary_image',
            field=models.ImageField(blank=True, upload_to='diary_images'),
        ),
    ]
