# Generated by Django 3.1.3 on 2020-12-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_post_diary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='What Happened?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='diary_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='diary_images', verbose_name='A Memorable Pic!'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='A Title to Describe Today'),
        ),
    ]
