# Generated by Django 3.1.3 on 2020-12-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201223_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='account_pics'),
        ),
    ]
