# Generated by Django 3.1.3 on 2020-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_motivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='What happened?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='diary_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='diary_images', verbose_name='A memorable pic!'),
        ),
        migrations.AlterField(
            model_name='post',
            name='motivation',
            field=models.CharField(blank=True, help_text="It doesn't have to be something big, it can be an upcoming trip,looking at the sunrise, another episode of drama coming out or even listening to music on the way to work! Try to not leave this blank so you can look back at it one day!", max_length=100, null=True, verbose_name='One thing motivating you for tomorrow'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='A title describing today'),
        ),
    ]
